# render.yaml
#
# Blueprint pour déployer T4ST3_M4TCH sur Render
# Instructions :
# 1. Poussez ce fichier sur GitHub à la racine du repository
# 2. Sur Render, créez une "Blueprint Instance" et sélectionnez votre repository
# 3. Ajoutez les variables d'environnement sensibles dans le dashboard Render

services:
  # Service Backend (Django API)
  - type: web
    name: tastematch-api
    runtime: docker
    plan: starter
    region: frankfurt
    repo: https://github.com/ybdn/T4ST3_M4TCH.git
    branch: main
    dockerContext: .
    dockerfilePath: ./.docker/backend/Dockerfile
    preDeployCommand: python manage.py migrate
    dockerCommand: gunicorn tastematch_api.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tastematch-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: tastematch-app
          property: url
      # Variables sensibles à ajouter manuellement dans Render
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: GOOGLE_BOOKS_API_KEY
        sync: false

  # Service Frontend (React App) - Site statique
  - type: web
    name: tastematch-app
    runtime: static
    repo: https://github.com/ybdn/T4ST3_M4TCH.git
    branch: main
    rootDir: ./frontend
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "./dist"
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: tastematch-api
          property: host

# Base de données PostgreSQL
databases:
  - name: tastematch-db
    plan: free
    region: frankfurt