# Generated by Django 5.2.1 on 2025-08-07 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description/Commentaire')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position dans la liste')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Élément de liste',
                'verbose_name_plural': 'Éléments de liste',
                'ordering': ['list', 'position'],
            },
        ),
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.CharField(choices=[('FILMS', 'Films'), ('SERIES', 'Séries'), ('MUSIQUE', 'Musique'), ('LIVRES', 'Livres')], default='FILMS', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('owner', 'category'), name='unique_list_per_category_per_user'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.list', verbose_name='Liste'),
        ),
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.UniqueConstraint(fields=('list', 'position'), name='unique_position_per_list'),
        ),
    ]
