# Generated by Django 5.2.1 on 2025-08-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apicache_externalreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='is_watched',
            field=models.BooleanField(default=False, verbose_name='Vu/Lu'),
        ),
    ]
