# Generated by Django 5.2.5 on 2025-08-10 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listitem_is_watched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Terminée'), ('paused', 'En pause')], default='active', max_length=20, verbose_name='Statut de la session')),
                ('current_round', models.PositiveIntegerField(default=1, verbose_name='Round actuel')),
                ('total_rounds', models.PositiveIntegerField(default=10, verbose_name='Total de rounds')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score total')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début de session')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de session')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session Versus',
                'verbose_name_plural': 'Sessions Versus',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VersusRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Numéro du round')),
                ('item_title', models.CharField(max_length=200, verbose_name="Titre de l'élément")),
                ('item_description', models.TextField(blank=True, verbose_name="Description de l'élément")),
                ('item_category', models.CharField(max_length=50, verbose_name='Catégorie')),
                ('item_poster_url', models.URLField(blank=True, null=True, verbose_name='URL du poster')),
                ('compatibility_score', models.PositiveIntegerField(default=0, verbose_name='Score de compatibilité')),
                ('user_choice', models.CharField(blank=True, choices=[('like', "J'aime"), ('dislike', "Je n'aime pas"), ('skip', 'Passer')], max_length=10, null=True, verbose_name="Choix de l'utilisateur")),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.versussession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Round Versus',
                'verbose_name_plural': 'Rounds Versus',
                'ordering': ['session', 'round_number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'round_number'), name='unique_round_per_session')],
            },
        ),
    ]
