# Generated by Django 5.2.5 on 2025-08-10 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listitem_is_watched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersusMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FILMS', 'Films'), ('SERIES', 'Séries'), ('MUSIQUE', 'Musique'), ('LIVRES', 'Livres')], max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('current_round', models.PositiveIntegerField(default=1, verbose_name='Round actuel')),
                ('total_rounds', models.PositiveIntegerField(default=10, verbose_name='Nombre total de rounds')),
                ('player1_score', models.PositiveIntegerField(default=0, verbose_name='Score joueur 1')),
                ('player2_score', models.PositiveIntegerField(default=0, verbose_name='Score joueur 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL, verbose_name='Joueur 1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL, verbose_name='Joueur 2')),
            ],
            options={
                'verbose_name': 'Match Versus',
                'verbose_name_plural': 'Matchs Versus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VersusRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Numéro du round')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'En cours'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_item1', to='core.listitem', verbose_name='Élément 1')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_item2', to='core.listitem', verbose_name='Élément 2')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.versusmatch', verbose_name='Match')),
            ],
            options={
                'verbose_name': 'Round Versus',
                'verbose_name_plural': 'Rounds Versus',
                'ordering': ['match', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='VersusChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du choix')),
                ('chosen_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listitem', verbose_name='Élément choisi')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Joueur')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.versusround', verbose_name='Round')),
            ],
            options={
                'verbose_name': 'Choix Versus',
                'verbose_name_plural': 'Choix Versus',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='versusround',
            constraint=models.UniqueConstraint(fields=('match', 'round_number'), name='unique_round_per_match'),
        ),
        migrations.AddConstraint(
            model_name='versuschoice',
            constraint=models.UniqueConstraint(fields=('round', 'player'), name='unique_choice_per_player_per_round'),
        ),
    ]
