# Generated by Django 5.2.5 on 2025-08-10 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listitem_is_watched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersusMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('finished', 'Terminé'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('compatibility_score', models.FloatField(blank=True, null=True, verbose_name='Score de compatibilité')),
                ('category', models.CharField(blank=True, choices=[('FILMS', 'Films'), ('SERIES', 'Séries'), ('MUSIQUE', 'Musique'), ('LIVRES', 'Livres')], max_length=20, null=True, verbose_name='Catégorie du match')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur 1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur 2')),
            ],
            options={
                'verbose_name': 'Match de goûts',
                'verbose_name_plural': 'Matchs de goûts',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user1', 'user2', 'category'), name='unique_match_per_category_per_users')],
            },
        ),
    ]
