# Generated by Django 5.2.5 on 2025-08-10 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listitem_is_watched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email de la personne invitée', max_length=254, verbose_name="Email de l'invité")),
                ('token', models.CharField(help_text="Token unique pour valider l'invitation", max_length=64, unique=True, verbose_name="Token d'invitation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(help_text='Date à laquelle le token expire', verbose_name="Date d'expiration")),
                ('used_at', models.DateTimeField(blank=True, help_text="Date à laquelle l'invitation a été utilisée", null=True, verbose_name="Date d'utilisation")),
                ('notes', models.TextField(blank=True, help_text='Notes administratives sur cette invitation', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, help_text='Administrateur qui a créé cette invitation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('used_by', models.OneToOneField(blank=True, help_text='Utilisateur qui a utilisé cette invitation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beta_invitation', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créé')),
            ],
            options={
                'verbose_name': 'Invitation bêta',
                'verbose_name_plural': 'Invitations bêta',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='core_betain_token_40e68c_idx'), models.Index(fields=['email'], name='core_betain_email_8816cd_idx'), models.Index(fields=['expires_at'], name='core_betain_expires_1f02e1_idx')],
            },
        ),
    ]
