# Generated by Django 5.2.5 on 2025-08-10 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listitem_is_watched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersusMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FILMS', 'Films'), ('SERIES', 'Séries'), ('MUSIQUE', 'Musique'), ('LIVRES', 'Livres')], max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('WAITING', 'En attente'), ('ACTIVE', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='WAITING', max_length=20, verbose_name='Statut')),
                ('current_round', models.PositiveIntegerField(default=1, verbose_name='Round actuel')),
                ('max_rounds', models.PositiveIntegerField(default=10, verbose_name='Nombre maximum de rounds')),
                ('completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Match Versus',
                'verbose_name_plural': 'Matchs Versus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VersusParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de participation')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.versusmatch', verbose_name='Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versus_participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Participant Versus',
                'verbose_name_plural': 'Participants Versus',
                'ordering': ['-score', 'joined_at'],
                'unique_together': {('match', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VersusRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Numéro du round')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'En cours'), ('COMPLETED', 'Terminé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_item1', to='core.listitem', verbose_name='Élément 1')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_item2', to='core.listitem', verbose_name='Élément 2')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.versusmatch', verbose_name='Match')),
                ('winner_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_rounds', to='core.listitem', verbose_name='Élément gagnant')),
            ],
            options={
                'verbose_name': 'Round Versus',
                'verbose_name_plural': 'Rounds Versus',
                'ordering': ['match', 'round_number'],
                'unique_together': {('match', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='VersusVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du vote')),
                ('chosen_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_votes', to='core.listitem', verbose_name='Élément choisi')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.versusparticipant', verbose_name='Participant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.versusround', verbose_name='Round')),
            ],
            options={
                'verbose_name': 'Vote Versus',
                'verbose_name_plural': 'Votes Versus',
                'ordering': ['voted_at'],
                'unique_together': {('round', 'participant')},
            },
        ),
    ]
