# Generated by Django 5.2.5 on 2025-08-10 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listitem_is_watched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalreference',
            name='user',
            field=models.ForeignKey(help_text='Denormalized from list_item.list.owner for faster queries', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_references', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='externalreference',
            index=models.Index(fields=['user', 'external_id'], name='user_external_id_idx'),
        ),
        migrations.AddIndex(
            model_name='externalreference',
            index=models.Index(fields=['user', 'external_source'], name='user_external_source_idx'),
        ),
    ]
