# Generated by Django 5.2.1 on 2025-08-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_friendmatch_friendship_matchsession_userpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du feature flag')),
                ('enabled', models.BooleanField(default=False, verbose_name='Activé')),
                ('rollout_percentage', models.PositiveIntegerField(default=0, verbose_name='Pourcentage de déploiement (0-100)')),
                ('description', models.TextField(blank=True, verbose_name='Description du flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_featur_name_d55661_idx'), models.Index(fields=['enabled'], name='core_featur_enabled_fdcd98_idx')],
            },
        ),
    ]
