# Generated by Django 5.2.5 on 2025-08-10 11:53

from django.db import migrations


def populate_user_field(apps, schema_editor):
    """Populate user field from list_item.list.owner"""
    ExternalReference = apps.get_model('core', 'ExternalReference')
    
    # Use select_related to avoid N+1 queries
    external_refs = ExternalReference.objects.select_related(
        'list_item__list__owner'
    ).filter(user__isnull=True)
    
    for external_ref in external_refs:
        external_ref.user = external_ref.list_item.list.owner
    
    # Bulk update for better performance
    if external_refs:
        ExternalReference.objects.bulk_update(external_refs, ['user'])


def reverse_populate_user_field(apps, schema_editor):
    """Reverse function - set user field to null"""
    ExternalReference = apps.get_model('core', 'ExternalReference')
    ExternalReference.objects.update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_user_to_external_reference_step1'),
    ]

    operations = [
        migrations.RunPython(
            populate_user_field,
            reverse_populate_user_field
        ),
    ]
